name: CI

on: 
  push:
    paths:
      - 'ge/**'
      - 'tests/**'
      - 'setup.py'
      - '.github/workflows/ci.yml'
  pull_request:
    paths:
      - 'ge/**'
      - 'tests/**'
      - 'setup.py'
      - '.github/workflows/ci.yml'
      
jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.8']
        tf-version: ['2.5.0', '2.6.0', '2.8.0', '2.9.0']

    steps:
    
    - uses: actions/checkout@v4
    
    - name: Setup python environment
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -q "numpy<1.24.0"
        pip install -q tensorflow==${{ matrix.tf-version }}
        pip install -q "protobuf>=3.19.0,<4.0.0"
        pip install -q requests
        pip install -e .

    - name: Test with pytest
      timeout-minutes: 20
      run: |
        pip install -q pytest
        pip install -q pytest-cov
        pip install -q python-coveralls
        pytest --cov=ge --cov-report=xml

    - name: Upload coverage to Codecov  
      uses: codecov/codecov-action@v4
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        file: ./coverage.xml
        flags: pytest
        name: py${{ matrix.python-version }}-tf${{ matrix.tf-version }}
